version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  web:
      build:
        context: ./drf_project
        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./drf_project:/src
      ports:
        - "8000:8000"
      env_file:
        - ./.env
      depends_on:
        - db
      links:
        - redis
  db:
    image: mysql:5.7.37
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_django
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql