version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker:9092"
    depends_on:
      - broker
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  db:
    platform: linux/x86_64
    image: mysql:5.7.37
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_django
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
  web:
      build:
        context: ./drf_project
        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./drf_project:/src
      ports:
        - "8000:8000"
      env_file:
        - ./.env
      depends_on:
        - db
      links:
        - redis
  dblogs:
    image: postgres:13.0-alpine
    volumes:
      - ./db_logs:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  logs:
    build:
      context: ./django_logs
      dockerfile: Dockerfile
    env_file:
      - ./.env.logs
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_logs:/src
    ports:
      - "8001:8000"
    depends_on:
      - dblogs