version: '3.8'

services:
  web:
      build: ./drf_project
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./drf_project/:/usr/src/drf_project/
      ports:
        - "8000:8000"
      env_file:
        - ./.env