version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - project

  db:
    platform: linux/x86_64
    image: mysql:5.7.37
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_django
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
    networks:
      - project

  web:
      build:
        context: ./drf_project
        dockerfile: Dockerfile
      container_name: web
#      entrypoint: ["./entrypoint.sh"]
#      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./drf_project:/src
      ports:
        - "8000:8000"
      expose:
        - "9092"
        - "9093"
        - "8001"
      env_file:
        - ./.env
      depends_on:
        - db
      links:
        - redis
      networks:
        - project

networks:
  project:
    name: project
    external: True