# Generated by Django 4.0.2 on 2022-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPHModel',
            fields=[
                ('userId', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('update_date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
